import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import {
  digest,
  isGenerated,
  parseGeneratedContext,
  parseInstructions,
  parsePreamble,
} from "../src/adoptparse.ts";

/*
 * The situation this exists for, in full.
 *
 * `.hq/CONTEXT.md` is generated from the database and overwrites whatever is
 * there. On this machine a project's five standing decisions — how deploys
 * work, which agent owns which files — lived only in that file, and survived
 * purely because no project happened to point at that directory any more.
 * Pointing one at it would have blanked them.
 *
 * The fixture below is the real file's shape, trimmed.
 */
const GENERATED_CONTEXT = `<!-- generated by Spaces — do not edit -->
# archii — context

> What this project is, and everything Spaces knows about it.

archii startup team

- Project: archii
- GitHub repo: archii-ai/archii-main

## Decisions

### Merging main never auto-ships

CI is path-filtered so each product builds only when its own directory
changes, but shipping is always an explicit action.

### iOS split: @codex owns the contract layer 📌

Both agents are live in the repo at once, so this is the working agreement.

## Notes

### A note

Something worth remembering.
`;

test("a generated context file gives its decisions back", () => {
  assert.ok(isGenerated(GENERATED_CONTEXT));
  const found = parseGeneratedContext(GENERATED_CONTEXT);

  assert.deepEqual(
    found.map((c) => [c.kind, c.title]),
    [
      ["decision", "Merging main never auto-ships"],
      ["decision", "iOS split: @codex owns the contract layer"],
      ["note", "A note"],
    ]
  );
  // The pin is Spaces' own decoration, not part of anybody's title.
  assert.ok(!found[1].title.includes("📌"));
  assert.match(found[0].content, /path-filtered/);

  // The preamble and the project facts are not candidates: Spaces holds those
  // in columns of its own, and adopting them would duplicate the project.
  assert.ok(!found.some((c) => c.content.includes("GitHub repo")));
  assert.ok(!found.some((c) => c.title === "archii — context"));
});

/*
 * The description is the one part of a generated CONTEXT.md that Spaces keeps
 * in a column rather than in memory — so nothing adopted it, and a project
 * created by pointing at an existing folder regenerated the file without it.
 * Observed live on archii: the line "archii startup team" was the only thing
 * the round trip lost.
 */
test("the description is read back into the column it came from", () => {
  assert.equal(parsePreamble(GENERATED_CONTEXT), "archii startup team");

  // The file's own furniture is not a description.
  assert.doesNotMatch(parsePreamble(GENERATED_CONTEXT), /regenerates|archii — context|Project:/);
  // Nothing to take is not a failure, and somebody else's file is not ours to read this way.
  const bare = GENERATED_CONTEXT.replace("archii startup team\n\n", "");
  assert.equal(parsePreamble(bare), "");
  assert.equal(parsePreamble("# archii\n\nA hand-written file.\n"), "");
});

test("a hand-written instructions file is split, never claimed as decisions", () => {
  const claude = `# archii

Some preamble about the repo.

## Build

Run \`npm run build\`. Never commit to main.

## Style

Two spaces, no semicolons.
`;
  const found = parseInstructions(claude, "CLAUDE.md");
  assert.deepEqual(
    found.map((c) => c.title),
    ["archii", "Build", "Style"]
  );
  // Somebody else's prose is context. Calling it a decision is a claim this
  // cannot check.
  assert.ok(found.every((c) => c.kind === "context"));
  assert.match(found[1].content, /npm run build/);
});

test("prose before the first heading is kept, and a file with none still counts", () => {
  const withPreamble = "Read the runbook first.\n\n## Deploys\n\nUse the script.\n";
  const found = parseInstructions(withPreamble, "AGENTS.md");
  assert.deepEqual(
    found.map((c) => c.title),
    ["AGENTS.md", "Deploys"]
  );
  assert.equal(found[0].content, "Read the runbook first.");

  const flat = parseInstructions("Just be careful with migrations.", "CLAUDE.md");
  assert.deepEqual(flat, [
    { title: "CLAUDE.md", content: "Just be careful with migrations.", kind: "context" },
  ]);

  // Nothing to adopt is not an error, and Spaces' own output is never adopted
  // as though somebody wrote it by hand.
  assert.deepEqual(parseInstructions("   \n\n", "CLAUDE.md"), []);
  assert.deepEqual(parseInstructions(GENERATED_CONTEXT, "CLAUDE.md"), []);
});

test("adopting twice adopts once, and an edit is a new thing", () => {
  const [first] = parseGeneratedContext(GENERATED_CONTEXT);
  assert.equal(digest(first), digest({ ...first }));
  // Reworded, retitled, or refiled: each is something the workspace has not
  // seen, which is what makes re-running safe rather than lossy.
  assert.notEqual(digest(first), digest({ ...first, content: `${first.content} And more.` }));
  assert.notEqual(digest(first), digest({ ...first, title: "Something else" }));
  assert.notEqual(digest(first), digest({ ...first, kind: "note" }));
});

/*
 * Adoption has to happen before the blackboard renders the database back out
 * over the file, or it cannot prevent the loss it exists to prevent. And it
 * must never remove anything: a section missing from a file somebody else
 * maintains is not evidence that the decision was reversed.
 */
test("context is read before it is overwritten, and nothing is ever deleted", async () => {
  const [blackboard, adopt] = await Promise.all([
    readFile(new URL("../src/blackboard.ts", import.meta.url), "utf8"),
    readFile(new URL("../src/adopt.ts", import.meta.url), "utf8"),
  ]);

  const generate = blackboard.slice(blackboard.indexOf("async function generate("));
  const adoptAt = generate.indexOf("adoptContext(project)");
  const writeAt = generate.indexOf("CONTEXT.md`, buildContext");
  assert.ok(adoptAt > 0, "generate() does not adopt");
  assert.ok(writeAt > 0, "generate() no longer writes CONTEXT.md");
  assert.ok(adoptAt < writeAt, "adoption must run before the overwrite");

  // Append-only, and it never edits files that belong to their authors.
  assert.doesNotMatch(adopt, /DELETE FROM|updateMemory|write_text_file/);
  assert.match(adopt, /INSERT OR IGNORE INTO adopted_context/);
  // A failure to adopt must not stop the mirror being written.
  assert.match(generate.slice(0, writeAt), /try \{\s*\n\s*await adoptContext/);
});

/*
 * The ledger is what makes adoption skip a section it has already brought in.
 * If it outlives the memory it describes, adoption refuses to restore context
 * that is no longer there — a silent failure, and the exact opposite of what
 * this layer exists for. Both paths that delete a project must clear it: the
 * one in the app, and the one a portal tombstone takes.
 */
test("deleting a project takes its adoption ledger with it", async () => {
  const [store, portal] = await Promise.all([
    readFile(new URL("../src/store.ts", import.meta.url), "utf8"),
    readFile(new URL("../src/portalContent.ts", import.meta.url), "utf8"),
  ]);

  for (const [name, src, from] of [
    ["deleteProject", store, "async deleteProject(id)"],
    ["removeRemoteMirror", portal, "async function removeRemoteMirror("],
  ] as const) {
    const body = src.slice(src.indexOf(from));
    const memoryAt = body.indexOf("DELETE FROM memory WHERE project_id");
    const ledgerAt = body.indexOf("DELETE FROM adopted_context WHERE project_id");
    assert.ok(memoryAt > 0, `${name} does not clear memory`);
    assert.ok(ledgerAt > 0, `${name} leaves the adoption ledger behind`);
    // Near the memory it belongs to, not somewhere else in the file.
    assert.ok(ledgerAt - memoryAt > 0 && ledgerAt - memoryAt < 400, `${name} clears the ledger somewhere unrelated`);
  }
});

/*
 * Adoption used to run only at startup and on agent runs, so a project created
 * mid-session — the exact moment somebody points Spaces at a folder that
 * already has a CLAUDE.md — sat un-adopted until something unrelated happened
 * to trigger a sync. Its context is wanted then, not later.
 */
test("pointing a project at a folder reads that folder", async () => {
  const store = await readFile(new URL("../src/store.ts", import.meta.url), "utf8");
  const add = store.slice(store.indexOf("async addProject("));
  const body = add.slice(0, add.indexOf("\n  async updateProject("));

  assert.match(body, /syncBlackboard\(proj\.id\)/);
  // Only when there is a folder to read, and never blocking the caller: this
  // returns the project, and the mirror catches up on its own.
  assert.match(body, /if \(proj\.local_path\.trim\(\)\)/);
  assert.match(body, /void import\("\.\/blackboard"\)/);
  assert.ok(
    body.indexOf("await get().refreshAll()") < body.indexOf("syncBlackboard"),
    "the project must exist in the store before its context is read into it"
  );
});
