/**
 * The shared blackboard.
 *
 * Spaces's coordination state lives in SQLite, which agent CLIs can't see. This
 * mirrors it into plain markdown under <project>/.hq/ so a Claude Code or
 * Codex process working in the repo can read the same picture of the project
 * with its own tools — and so the picture survives in git history.
 *
 * Output is deterministic: the same database state produces byte-identical
 * files, and unchanged files are not rewritten at all. That keeps git diffs
 * meaningful and stops file watchers from thrashing.
 */
import { invoke } from "@tauri-apps/api/core";
import { getDb } from "./db";
import { slug } from "./types";
import type {
  Agent, Assignment, Channel, ChannelMember, EntityRef, Link, MemoryEntry, MemoryKind,
  Project, Task, TaskStatus, Team, TeamMember,
} from "./types";
import { LINK_KIND_BY_ID } from "./links";
import { ACTIONS_DOC, ensureActionsFile } from "./actions";
import { setupMcp } from "./mcpsetup";
import { isGitRepo } from "./workspaces";

export interface BlackboardResult {
  /** Files actually rewritten, relative to the project root. */
  written: string[];
  /**
   * True when the repo already has a hand-written AGENTS.md or CLAUDE.md. Spaces
   * never touches those; the UI should offer to add POINTER_LINE instead.
   */
  suggestPointer: boolean;
  /** Non-fatal problems (a file that couldn't be written, etc.). */
  errors: string[];
}

/** Suggested one-liner for a user-owned AGENTS.md / CLAUDE.md. */
export const POINTER_LINE =
  "Shared project context lives in `.hq/` — read `.hq/CONTEXT.md`, `.hq/ROSTER.md`, `.hq/BOARD.md` and `.hq/LINKS.md` before starting work (generated by Spaces).";

const DIR = ".hq";
/** First line of every generated file; also how we recognise our own AGENTS.md. */
const MARKER = "<!-- generated by Spaces — do not edit -->";

const MEMORY_KINDS: MemoryKind[] = ["decision", "context", "note"];
const MEMORY_HEADINGS: Record<MemoryKind, string> = {
  decision: "Decisions",
  context: "Context",
  note: "Notes",
};
const BOARD_COLUMNS: TaskStatus[] = ["backlog", "todo", "doing", "done"];
const BOARD_HEADINGS: Record<TaskStatus, string> = {
  backlog: "Backlog",
  todo: "To do",
  doing: "In progress",
  done: "Done",
};

/* ------------------------------------------------------------------ text -- */

/**
 * The handle an agent actually answers to. Must stay identical to
 * resolveTargets() in agents.ts, which matches mentions on slug(name) — a name
 * that slugs to nothing (e.g. all non-ASCII) simply isn't mentionable, and the
 * blackboard must not pretend otherwise.
 */
function handle(agent: Agent): string {
  return slug(agent.name);
}

function mention(agent: Agent): string {
  const h = handle(agent);
  return h ? `@${h}` : `**${oneLine(agent.name)}**`;
}

/** Collapse to a single line — table cells and list items can't hold newlines. */
function oneLine(s: string): string {
  return (s ?? "").replace(/\s+/g, " ").trim();
}

function cell(s: string): string {
  const t = oneLine(s).replace(/\|/g, "\\|");
  return t || "—";
}

/** Normalise a free-text block so identical content always renders identically. */
function block(s: string): string {
  return (s ?? "")
    .replace(/\r\n?/g, "\n")
    .split("\n")
    .map((l) => l.replace(/\s+$/, ""))
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function header(title: string, what: string): string[] {
  return [
    MARKER,
    `# ${title}`,
    "",
    `> ${what}`,
    "> Spaces regenerates this file from its database and overwrites local edits —",
    "> change it in the Spaces app, not here.",
    "",
  ];
}

/** Exactly one trailing newline, no trailing blank lines. */
function finish(lines: string[]): string {
  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}

/* -------------------------------------------------------------- builders -- */

function buildContext(project: Project, memory: MemoryEntry[]): string {
  const lines = header(
    `${oneLine(project.name) || "Project"} — context`,
    "What this project is, and everything Spaces knows about it."
  );

  const desc = block(project.description);
  if (desc) lines.push(desc, "");

  const facts: string[] = [`- Project: ${cell(project.name)}`];
  if (oneLine(project.repo)) facts.push(`- GitHub repo: ${cell(project.repo)}`);
  lines.push(...facts, "");

  const instructions = block(project.instructions);
  if (instructions) lines.push("## Standing instructions", "", instructions, "");

  // Known kinds in a fixed order, then anything unexpected, so a stray kind
  // never silently disappears from the blackboard.
  const extraKinds = [...new Set(memory.map((m) => m.kind))]
    .filter((k) => !MEMORY_KINDS.includes(k))
    .sort();
  for (const kind of [...MEMORY_KINDS, ...extraKinds]) {
    const entries = memory.filter((m) => m.kind === kind);
    if (!entries.length) continue;
    lines.push(`## ${MEMORY_HEADINGS[kind as MemoryKind] ?? oneLine(kind)}`, "");
    for (const e of entries) {
      lines.push(`### ${oneLine(e.title) || "Untitled"}${e.pinned ? " 📌" : ""}`, "");
      const body = block(e.content);
      if (body) lines.push(body, "");
    }
  }

  if (!desc && !instructions && !memory.length) {
    lines.push("_No description, instructions or memory recorded yet._", "");
  }
  return finish(lines);
}

function buildRoster(
  project: Project,
  agents: Agent[],
  channelsOf: Map<string, string[]>,
  teamsOf: Map<string, string[]>,
  teams: Team[],
  membersOfTeam: Map<string, Agent[]>
): string {
  const lines = header(
    `${oneLine(project.name) || "Project"} — roster`,
    "Who works on this project, what they own, and where they talk."
  );

  if (!agents.length) {
    lines.push("_No agents are members of this project's channels yet._", "");
    return finish(lines);
  }

  lines.push(
    "| Agent | Handle | Role | Owns | Backend | Channels | Teams |",
    "| --- | --- | --- | --- | --- | --- | --- |"
  );
  for (const a of agents) {
    lines.push(
      `| ${cell(a.name)} | ${cell(handle(a) ? `@${handle(a)}` : "")} | ${cell(a.role)} | ${cell(a.owns)} | ${cell(a.kind)} | ` +
        `${cell((channelsOf.get(a.id) ?? []).map((n) => `#${n}`).join(", "))} | ` +
        `${cell((teamsOf.get(a.id) ?? []).join(", "))} |`
    );
  }
  const example = agents.find((a) => handle(a));
  if (example) {
    lines.push("", `Mention a teammate by handle (e.g. \`@${handle(example)}\`) to hand work to them.`, "");
  } else {
    lines.push("");
  }

  if (teams.length) {
    lines.push("## Teams", "");
    for (const t of teams) {
      lines.push(`### ${oneLine(t.name) || "Team"}`, "");
      const members = membersOfTeam.get(t.id) ?? [];
      lines.push(`Members: ${members.length ? members.map(mention).join(", ") : "—"}`, "");
      const desc = block(t.description);
      if (desc) lines.push(desc, "");
      const charter = block(t.charter);
      if (charter) lines.push("Charter:", "", charter, "");
    }
  }
  return finish(lines);
}

/**
 * The connection graph, as something an agent can read with `cat`.
 *
 * Injecting this into the prompt is the volatile half; this is the durable
 * one. An agent working in the repo can open the file, follow a link to the
 * memory entry that explains a decision, and see who is accountable — without
 * Spaces having decided in advance that this turn needed that context.
 *
 * Scoped to the project: a link whose ends both live elsewhere is somebody
 * else's business and would only be noise in this repo.
 */
function buildLinks(
  project: Project,
  links: Link[],
  assignments: Assignment[],
  label: (ref: EntityRef) => string | null
): string {
  const lines = header(
    `Connections — ${project.name}`,
    "What is connected to what, and who is accountable for it."
  );

  const rows: string[] = [];
  for (const l of links) {
    const from = label({ type: l.from_type, id: l.from_id });
    const to = label({ type: l.to_type, id: l.to_id });
    // Both ends must resolve inside this project, or the row would name
    // something the reader has no way to look up.
    if (!from || !to) continue;
    const spec = LINK_KIND_BY_ID[l.kind] ?? LINK_KIND_BY_ID.relates;
    rows.push(`| ${cell(from)} | ${spec.label} | ${cell(to)} | ${cell(l.note)} |`);
  }
  if (rows.length) {
    lines.push("## Links", "", "| From | Relation | To | Note |", "| --- | --- | --- | --- |", ...rows, "");
  }

  const owned: string[] = [];
  for (const a of assignments) {
    const who = label({ type: a.subject_type, id: a.subject_id });
    const what = label({ type: a.target_type, id: a.target_id });
    if (!who || !what) continue;
    owned.push(`| ${cell(who)} | ${a.role} | ${cell(what)} |`);
  }
  if (owned.length) {
    lines.push("## Who is on what", "", "| Who | Role | What |", "| --- | --- | --- |", ...owned, "");
  }

  if (!rows.length && !owned.length) {
    lines.push("Nothing is linked yet.", "");
  }
  return finish(lines);
}

function buildBoard(project: Project, tasks: Task[], byId: Map<string, Agent>): string {
  const lines = header(
    `${oneLine(project.name) || "Project"} — board`,
    "The current task board. Checked items are done."
  );

  const extraStatuses = [...new Set(tasks.map((t) => t.status))]
    .filter((s) => !BOARD_COLUMNS.includes(s))
    .sort();
  for (const status of [...BOARD_COLUMNS, ...extraStatuses]) {
    const group = tasks.filter((t) => t.status === status);
    lines.push(`## ${BOARD_HEADINGS[status as TaskStatus] ?? oneLine(status)}`, "");
    if (!group.length) {
      lines.push("_Nothing here._", "");
      continue;
    }
    for (const t of group) lines.push(taskLine(t, byId));
    lines.push("");
  }
  return finish(lines);
}

function taskLine(t: Task, byId: Map<string, Agent>): string {
  const owner = byId.get(t.assignee_agent_id);
  const bits: string[] = [];
  if (oneLine(t.due_date)) bits.push(`due ${oneLine(t.due_date)}`);
  if (oneLine(t.branch)) bits.push(`branch ${oneLine(t.branch)}`);
  const suffix = [
    owner ? `— ${mention(owner)}` : "",
    bits.length ? `(${bits.join(", ")})` : "",
  ]
    .filter(Boolean)
    .join(" ");
  return `- [${t.status === "done" ? "x" : " "}] ${oneLine(t.title) || "Untitled"}${suffix ? ` ${suffix}` : ""}`;
}

function buildChannel(
  channel: Channel,
  lead: Agent | undefined,
  agents: Agent[],
  teams: Team[],
  membersOfTeam: Map<string, Agent[]>
): string {
  const lines = header(
    `#${oneLine(channel.name) || "channel"}`,
    "What this channel is for, how it dispatches work, and who is in it."
  );

  const facts = [`- Mode: ${cell(channel.mode)}`];
  if (oneLine(channel.topic)) facts.push(`- Topic: ${cell(channel.topic)}`);
  if (lead) facts.push(`- Lead: @${handle(lead)}`);
  facts.push(`- Agent-to-agent chaining: ${channel.chaining ? "on" : "off"}`);
  lines.push(...facts, "");

  const charter = block(channel.charter);
  if (charter) lines.push("## Charter", "", charter, "");

  lines.push("## Members", "");
  if (!agents.length && !teams.length) {
    lines.push("_No members yet._", "");
  } else {
    for (const a of agents) {
      const extras = [oneLine(a.role), a.kind, oneLine(a.owns) ? `owns ${oneLine(a.owns)}` : ""]
        .filter(Boolean)
        .join(" · ");
      const who = handle(a) ? `@${handle(a)} — ${oneLine(a.name)}` : `**${oneLine(a.name)}**`;
      lines.push(`- ${who}${extras ? ` (${extras})` : ""}`);
    }
    for (const t of teams) {
      const members = (membersOfTeam.get(t.id) ?? []).map(mention).join(", ");
      lines.push(`- Team **${oneLine(t.name)}** — ${members || "no members"}`);
    }
    lines.push("");
  }
  return finish(lines);
}

function buildAgentsMd(project: Project): string {
  return finish([
    MARKER,
    "# Agents",
    "",
    `This repository is coordinated with Spaces${oneLine(project.name) ? ` for the "${oneLine(project.name)}" project` : ""}.`,
    "Shared, always-current project context lives in `.hq/`:",
    "",
    "- `.hq/CONTEXT.md` — what the project is, standing instructions, decisions and notes.",
    "- `.hq/ROSTER.md` — the agents on this project, what each owns, and which channels they're in.",
    "- `.hq/BOARD.md` — the task board.",
    "- `.hq/LINKS.md` — what is connected to what, and who is accountable for it.",
    "- `.hq/actions.jsonl` — how you CHANGE any of the above. Read `.hq/ACTIONS.md`.",
    "- `.hq/channels/*.md` — each channel's charter, mode and members.",
    "",
    "Read `CONTEXT.md`, `ROSTER.md` and `BOARD.md` before starting work, and respect the",
    "ownership boundaries in the roster.",
    "",
    "Spaces regenerates everything under `.hq/` from its own database — edit it in the Spaces app,",
    "not by hand. This file is generated too; delete it if you'd rather write your own.",
  ]);
}

/* -------------------------------------------------------------- file i/o -- */

type FileState = { kind: "file"; text: string } | { kind: "missing" } | { kind: "unknown" };

async function statFile(root: string, rel: string): Promise<FileState> {
  try {
    return { kind: "file", text: await invoke<string>("read_text_file", { root, relativePath: rel }) };
  } catch (e) {
    // Only a definite "not there" counts as missing — anything else (perms, a
    // binary file) must not be treated as an invitation to overwrite.
    return /no such file|not found|os error 2/i.test(String(e)) ? { kind: "missing" } : { kind: "unknown" };
  }
}

/** Write only when the bytes actually change, so a sync is a true no-op. */
async function writeIfChanged(root: string, rel: string, contents: string, out: BlackboardResult) {
  try {
    const cur = await statFile(root, rel);
    if (cur.kind === "file" && cur.text === contents) return;
    await invoke("write_text_file", { root, relativePath: rel, contents });
    out.written.push(rel);
  } catch (e) {
    out.errors.push(`${rel}: ${String(e)}`);
  }
}

/* ----------------------------------------------------------------- sync -- */

const chains = new Map<string, Promise<unknown>>();
const timers = new Map<string, ReturnType<typeof setTimeout>>();
const DEBOUNCE_MS = 1500;

/**
 * Regenerate <project>/.hq/ from the database. No-ops (returns an empty
 * result) when the project has no local path or that path isn't a git repo.
 * Safe to call as often as you like; only changed files are written.
 */
export function syncBlackboard(projectId: string): Promise<BlackboardResult> {
  // Serialise per project: two overlapping syncs would race on the same files.
  const run = () => runSync(projectId);
  const prev = chains.get(projectId);
  const next = prev ? prev.then(run, run) : run();
  const guard = next.then(
    () => undefined,
    () => undefined
  );
  chains.set(projectId, guard);
  void guard.then(() => {
    if (chains.get(projectId) === guard) chains.delete(projectId);
  });
  return next;
}

/** Fire-and-forget version for mutation paths — cheap to call on every write. */
export function scheduleBlackboardSync(projectId: string, delayMs = DEBOUNCE_MS): void {
  const pending = timers.get(projectId);
  if (pending) clearTimeout(pending);
  timers.set(
    projectId,
    setTimeout(() => {
      timers.delete(projectId);
      void syncBlackboard(projectId).catch(() => {
        // best-effort: the blackboard is a mirror, never the source of truth
      });
    }, delayMs)
  );
}

/** Never rejects — a mirror of the database must not break its callers. */
async function runSync(projectId: string): Promise<BlackboardResult> {
  const out: BlackboardResult = { written: [], suggestPointer: false, errors: [] };
  try {
    await generate(projectId, out);
  } catch (e) {
    out.errors.push(String(e));
  }
  return out;
}

async function generate(projectId: string, out: BlackboardResult): Promise<void> {
  const db = await getDb();
  const [project] = await db.select<Project[]>("SELECT * FROM projects WHERE id = $1", [projectId]);
  const root = (project?.local_path ?? "").trim();
  if (!project || !root) return;
  if (!(await isGitRepo(root))) return;

  // Every query is explicitly ordered: the files must be byte-stable.
  const [channels, tasks, memory, agents, teams, links, assignments, teamMembers] = await Promise.all([
    db.select<Channel[]>("SELECT * FROM channels WHERE project_id = $1 ORDER BY name, id", [projectId]),
    db.select<Task[]>("SELECT * FROM tasks WHERE project_id = $1 ORDER BY sort_order, created_at, id", [projectId]),
    db.select<MemoryEntry[]>(
      "SELECT * FROM memory WHERE project_id = $1 ORDER BY pinned DESC, created_at, id",
      [projectId]
    ),
    db.select<Agent[]>("SELECT * FROM agents ORDER BY name, id"),
    db.select<Team[]>("SELECT * FROM teams ORDER BY name, id"),
    db.select<Link[]>("SELECT * FROM links ORDER BY created_at, id"),
    db.select<Assignment[]>("SELECT * FROM assignments ORDER BY created_at, id"),
    db.select<TeamMember[]>("SELECT * FROM team_members"),
  ]);

  let channelMembers: ChannelMember[] = [];
  if (channels.length) {
    const ids = channels.map((c) => c.id);
    const ph = ids.map((_, i) => `$${i + 1}`).join(",");
    channelMembers = await db.select<ChannelMember[]>(
      `SELECT * FROM channel_members WHERE channel_id IN (${ph})`,
      ids
    );
  }

  const agentById = new Map(agents.map((a) => [a.id, a] as const));
  const teamById = new Map(teams.map((t) => [t.id, t] as const));
  // Membership tables are unordered, so every derived list is re-sorted into
  // the query's order (name, id) — locale-independent, hence byte-stable.
  const agentOrder = new Map(agents.map((a, i) => [a.id, i] as const));
  const teamOrder = new Map(teams.map((t, i) => [t.id, i] as const));
  const byAgent = (a: Agent, b: Agent) => (agentOrder.get(a.id) ?? 0) - (agentOrder.get(b.id) ?? 0);
  const byTeam = (a: Team, b: Team) => (teamOrder.get(a.id) ?? 0) - (teamOrder.get(b.id) ?? 0);
  const membersOfTeam = new Map<string, Agent[]>(
    teams.map((t) => [
      t.id,
      teamMembers
        .filter((tm) => tm.team_id === t.id)
        .map((tm) => agentById.get(tm.agent_id))
        .filter((a): a is Agent => !!a)
        .sort(byAgent),
    ])
  );

  // Roster membership: direct channel members plus everyone reached via a team.
  const channelsOf = new Map<string, string[]>();
  const teamsOf = new Map<string, string[]>();
  const rosterIds = new Set<string>();
  const projectTeamIds = new Set<string>();
  const directOf = new Map<string, Agent[]>();
  const teamsInChannel = new Map<string, Team[]>();

  for (const c of channels) {
    const rows = channelMembers.filter((m) => m.channel_id === c.id);
    const direct = rows
      .filter((m) => m.member_type === "agent")
      .map((m) => agentById.get(m.member_id))
      .filter((a): a is Agent => !!a)
      .sort(byAgent);
    const cTeams = rows
      .filter((m) => m.member_type === "team")
      .map((m) => teamById.get(m.member_id))
      .filter((t): t is Team => !!t)
      .sort(byTeam);
    directOf.set(c.id, direct);
    teamsInChannel.set(c.id, cTeams);

    for (const t of cTeams) projectTeamIds.add(t.id);
    const viaTeams = cTeams.flatMap((t) => membersOfTeam.get(t.id) ?? []);
    for (const a of [...direct, ...viaTeams]) {
      rosterIds.add(a.id);
      push(channelsOf, a.id, c.name);
    }
    for (const t of cTeams) {
      for (const a of membersOfTeam.get(t.id) ?? []) push(teamsOf, a.id, t.name);
    }
  }

  const roster = agents.filter((a) => rosterIds.has(a.id));
  const projectTeams = teams.filter((t) => projectTeamIds.has(t.id));

  await writeIfChanged(root, `${DIR}/CONTEXT.md`, buildContext(project, memory), out);
  await writeIfChanged(
    root,
    `${DIR}/ROSTER.md`,
    buildRoster(project, roster, channelsOf, teamsOf, projectTeams, membersOfTeam),
    out
  );
  await writeIfChanged(root, `${DIR}/BOARD.md`, buildBoard(project, tasks, agentById), out);
  /**
   * Name an entity from the rows already loaded, or null when it does not
   * belong to this project. Deliberately not describeEntity(): that reads the
   * zustand store, and this generator has to be a pure function of the
   * database so the files stay byte-stable no matter what the UI is showing.
   */
  const labelFor = (ref: EntityRef): string | null => {
    switch (ref.type) {
      case "project":
        return ref.id === project.id ? project.name : null;
      case "channel": {
        const c = channels.find((x) => x.id === ref.id);
        return c ? `#${c.name}` : null;
      }
      case "task": {
        const t = tasks.find((x) => x.id === ref.id);
        return t ? t.title : null;
      }
      case "memory": {
        const m = memory.find((x) => x.id === ref.id);
        return m ? `${m.title} (${m.kind})` : null;
      }
      case "agent": {
        const a = agentById.get(ref.id);
        return a ? mention(a) : null;
      }
      case "team": {
        const t = teams.find((x) => x.id === ref.id);
        return t ? `${t.name} team` : null;
      }
      // Global by nature: a pull request or issue is worth naming in any
      // project's file, because the id carries everything needed to find it.
      case "pr":
        return `PR ${ref.id}`;
      case "issue":
        return `issue ${ref.id}`;
      case "repo":
        return ref.id;
      default:
        return null;
    }
  };

  await writeIfChanged(
    root,
    `${DIR}/LINKS.md`,
    buildLinks(project, links, assignments, labelFor),
    out
  );

  // The write path. Reading the mirror makes an agent informed; this is what
  // makes it a member — the same operations a person performs in the UI,
  // reachable from inside its own harness.
  await writeIfChanged(root, `${DIR}/ACTIONS.md`, ACTIONS_DOC, out);
  await ensureActionsFile(project, root).catch((e) => out.errors.push(String(e)));
  try {
    const mcp = await setupMcp(project, root);
    for (const w of [mcp.server, mcp.tools, mcp.permissions]) {
      if (w.written) out.written.push(w.path);
      if (w.error) out.errors.push(w.error);
    }
  } catch (e) {
    // A harness without MCP is still perfectly usable through the file drop,
    // so this must degrade rather than fail the whole sync.
    out.errors.push(`MCP setup: ${String(e)}`);
  }

  // Channel names are slugged for the filesystem and can collide ("UI" and
  // "ui"); disambiguate with the id so no channel's file eats another's.
  const used = new Set<string>();
  for (const c of channels) {
    let name = slug(c.name) || "channel";
    if (used.has(name)) name = `${name}-${c.id.slice(0, 6)}`;
    used.add(name);
    await writeIfChanged(
      root,
      `${DIR}/channels/${name}.md`,
      buildChannel(
        c,
        agentById.get(c.lead_agent_id),
        directOf.get(c.id) ?? [],
        teamsInChannel.get(c.id) ?? [],
        membersOfTeam
      ),
      out
    );
  }

  // AGENTS.md / CLAUDE.md belong to the user. Only ever create our own, or
  // refresh one we previously generated (recognisable by the marker).
  const claude = await statFile(root, "CLAUDE.md");
  const agentsMd = await statFile(root, "AGENTS.md");
  const ownsClaude = claude.kind !== "missing" && !(claude.kind === "file" && claude.text.startsWith(MARKER));
  const ownsAgents = agentsMd.kind !== "missing" && !(agentsMd.kind === "file" && agentsMd.text.startsWith(MARKER));
  if (ownsClaude || ownsAgents) {
    out.suggestPointer = true;
  } else {
    await writeIfChanged(root, "AGENTS.md", buildAgentsMd(project), out);
  }
}

function push(map: Map<string, string[]>, key: string, value: string) {
  const list = map.get(key);
  if (!list) {
    map.set(key, [value]);
  } else if (!list.includes(value)) {
    list.push(value);
  }
}

/**
 * Mirror every project that has a checkout.
 *
 * Called at startup and after an agent turn. Without this the whole blackboard
 * was dead code: scheduleBlackboardSync had no callers, so `.hq/` — the shared
 * context agents read, the action protocol they write through, and the MCP
 * registration that makes their tools reachable — was never written at all.
 * A workspace could run for weeks with the write path installed and inert.
 *
 * Cheap to repeat: each file is compared before writing and unchanged ones are
 * skipped, and the per-project sync is debounced.
 */
export async function syncAllProjects(delayMs = 400): Promise<void> {
  try {
    const db = await getDb();
    const rows = await db.select<{ id: string }[]>(
      "SELECT id FROM projects WHERE TRIM(local_path) != '' ORDER BY created_at"
    );
    // Each project's sync is a burst of ~20 IPC round trips — a git probe, a
    // dozen file comparisons, the MCP install and two config merges. Fired at
    // launch across every project they queue ahead of whatever the user does
    // first, and typing a message goes through the same IPC channel, so the
    // app feels slow at exactly the moment it is being judged.
    //
    // So: wait for the window to go idle, then space them a full second apart.
    // The mirror only has to be current before an agent reads it, which is
    // seconds away at the earliest and re-synced after every turn anyway.
    const start = () => rows.forEach((r, i) => scheduleBlackboardSync(r.id, delayMs + i * 1000));
    const idle = (window as unknown as {
      requestIdleCallback?: (cb: () => void, o?: { timeout: number }) => void;
    }).requestIdleCallback;
    if (idle) idle(start, { timeout: 8000 });
    else window.setTimeout(start, 2500);
  } catch {
    // The mirror is best-effort; never let it break startup.
  }
}
