import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawn } from "node:child_process";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";

const server = new URL("./hq-mcp-server.mjs", import.meta.url);

test("lists and approval-queues the social publishing tool", async () => {
  const root = await mkdtemp(join(tmpdir(), "spaces-mcp-"));
  await mkdir(join(root, ".hq"));
  await writeFile(
    join(root, ".hq", "mcp-tools.json"),
    `${JSON.stringify({
      version: 1,
      tools: [
        {
          name: "spaces_publish_social",
          description: "Publish through a connected account.",
          effect: "propose",
          readOnly: false,
          inputSchema: {
            type: "object",
            properties: {
              platform: { type: "string", enum: ["instagram", "tiktok"] },
              copy: { type: "string" },
              media_url: { type: "string" },
              media_path: { type: "string" },
            },
            required: ["platform", "copy"],
            additionalProperties: false,
          },
        },
      ],
    }, null, 2)}\n`,
  );

  const child = spawn(process.execPath, [server.pathname, root], {
    cwd: root,
    env: {
      ...process.env,
      SPACES_PROJECT_ID: "project-1",
      SPACES_DB_PATH: join(root, "missing-spaces.db"),
    },
    stdio: ["pipe", "pipe", "pipe"],
  });
  let stdout = "";
  let stderr = "";
  child.stdout.setEncoding("utf8").on("data", (chunk) => {
    stdout += chunk;
  });
  child.stderr.setEncoding("utf8").on("data", (chunk) => {
    stderr += chunk;
  });

  const send = (message) => child.stdin.write(`${JSON.stringify(message)}\n`);
  send({
    jsonrpc: "2.0",
    id: 1,
    method: "initialize",
    params: { protocolVersion: "2024-11-05", capabilities: {} },
  });
  send({ jsonrpc: "2.0", id: 2, method: "tools/list" });
  send({
    jsonrpc: "2.0",
    id: 3,
    method: "tools/call",
    params: {
      name: "spaces_publish_social",
      arguments: {
        platform: "instagram",
        copy: "A reviewed launch post",
        media_path: "assets/social/launch.png",
      },
    },
  });
  child.stdin.end();

  const exitCode = await new Promise((resolve, reject) => {
    child.once("error", reject);
    child.once("close", resolve);
  });
  assert.equal(exitCode, 0, stderr);

  const responses = stdout.trim().split("\n").map((line) => JSON.parse(line));
  assert.equal(responses[0].result.serverInfo.name, "hq");
  assert.match(responses[0].result.instructions, /operating inside Spaces/);
  assert.match(responses[0].result.instructions, /final assistant response is posted/);
  assert.equal(responses[1].result.tools[0].name, "spaces_publish_social");
  assert.match(responses[1].result.tools[0].description, /human to approve/i);
  assert.match(responses[2].result.content[0].text, /holding it for a human to approve/i);

  const queued = JSON.parse(
    (await readFile(join(root, ".hq", "actions.jsonl"), "utf8")).trim(),
  );
  assert.equal(queued.op, "spaces_publish_social");
  assert.equal(queued.project_id, "project-1");
  assert.deepEqual(queued.args, {
    platform: "instagram",
    copy: "A reviewed launch post",
    media_path: "assets/social/launch.png",
  });
});

test("searches and reads generated Knowledge by stable path reference", async () => {
  const root = await mkdtemp(join(tmpdir(), "spaces-knowledge-mcp-"));
  await mkdir(join(root, ".hq"));
  await writeFile(
    join(root, ".hq", "mcp-tools.json"),
    `${JSON.stringify({
      version: 1,
      tools: [
        {
          name: "spaces_search_knowledge",
          description: "Search shared Knowledge.",
          effect: "auto",
          readOnly: true,
          inputSchema: {
            type: "object",
            properties: { query: { type: "string" } },
            required: ["query"],
            additionalProperties: false,
          },
        },
        {
          name: "spaces_read_knowledge",
          description: "Read shared Knowledge.",
          effect: "auto",
          readOnly: true,
          inputSchema: {
            type: "object",
            properties: { ref: { type: "string" } },
            required: ["ref"],
            additionalProperties: false,
          },
        },
      ],
    }, null, 2)}\n`,
  );
  const ref = "knowledge:company:Operations%2FRunbooks%2FDeploy.md";
  await writeFile(
    join(root, ".hq", "KNOWLEDGE.md"),
    [
      "<!-- generated by Spaces — do not edit -->",
      "# Workspace knowledge",
      "",
      `<!-- spaces-knowledge-ref: ${ref} -->`,
      "### Deploy",
      "",
      "- Source: Company vault",
      "- Path: `Operations/Runbooks/Deploy.md`",
      "- Updated: 2026-07-26T00:00:00.000Z",
      "",
      "Deploy through the signed release workflow.",
      "",
    ].join("\n"),
  );

  const child = spawn(process.execPath, [server.pathname, root], {
    cwd: root,
    stdio: ["pipe", "pipe", "pipe"],
  });
  let stdout = "";
  let stderr = "";
  child.stdout.setEncoding("utf8").on("data", (chunk) => {
    stdout += chunk;
  });
  child.stderr.setEncoding("utf8").on("data", (chunk) => {
    stderr += chunk;
  });
  const send = (message) =>
    child.stdin.write(`${JSON.stringify(message)}\n`);
  send({
    jsonrpc: "2.0",
    id: 1,
    method: "initialize",
    params: { protocolVersion: "2024-11-05", capabilities: {} },
  });
  send({
    jsonrpc: "2.0",
    id: 2,
    method: "tools/call",
    params: {
      name: "spaces_search_knowledge",
      arguments: { query: "signed release" },
    },
  });
  send({
    jsonrpc: "2.0",
    id: 3,
    method: "tools/call",
    params: {
      name: "spaces_read_knowledge",
      arguments: { ref },
    },
  });
  child.stdin.end();

  const exitCode = await new Promise((resolve, reject) => {
    child.once("error", reject);
    child.once("close", resolve);
  });
  assert.equal(exitCode, 0, stderr);
  const responses = stdout.trim().split("\n").map((line) => JSON.parse(line));
  assert.match(
    responses[1].result.content[0].text,
    /Operations\/Runbooks\/Deploy\.md/,
  );
  assert.match(responses[1].result.content[0].text, /knowledge:company:/);
  assert.match(responses[2].result.content[0].text, /Cite this note/);
  assert.match(
    responses[2].result.content[0].text,
    /signed release workflow/,
  );
});

test("lists and reads the canonical Content Studio snapshot", async () => {
  const root = await mkdtemp(join(tmpdir(), "spaces-content-"));
  await mkdir(join(root, ".hq"));
  await writeFile(
    join(root, ".hq", "mcp-tools.json"),
    `${JSON.stringify({
      version: 1,
      tools: [
        {
          name: "spaces_list_content",
          description: "List Content Studio.",
          effect: "auto",
          readOnly: true,
          inputSchema: {
            type: "object",
            properties: {
              project: { type: "string" },
              status: { type: "string" },
              query: { type: "string" },
            },
            additionalProperties: false,
          },
        },
        {
          name: "spaces_get_content",
          description: "Read a Content Studio card.",
          effect: "auto",
          readOnly: true,
          inputSchema: {
            type: "object",
            properties: { content: { type: "string" } },
            required: ["content"],
            additionalProperties: false,
          },
        },
      ],
    }, null, 2)}\n`,
  );
  await writeFile(
    join(root, ".hq", "CONTENT.md"),
    [
      "<!-- generated by Spaces — do not edit -->",
      "# Content Studio",
      "",
      "<!-- spaces-content-ref: content:card-1 -->",
      "### Launch post",
      "",
      "- Project: archii",
      "- Project ID: `project-1`",
      "- Status: review",
      "- Platform: instagram",
      "- Campaign: Reveal",
      "- Owner: Codex",
      "- Connection: `connection-1`",
      "- Scheduled: Not scheduled",
      "- Media: https://example.com/launch.png",
      "- Published: Not published",
      "",
      "#### Brief",
      "",
      "Introduce the instrument.",
      "",
      "#### Copy",
      "",
      "Something is coming.",
      "",
    ].join("\n"),
  );

  const child = spawn(process.execPath, [server.pathname, root], {
    cwd: root,
    env: {
      ...process.env,
      SPACES_PROJECT_ID: "project-1",
      SPACES_DB_PATH: join(root, "missing-spaces.db"),
    },
    stdio: ["pipe", "pipe", "pipe"],
  });
  let stdout = "";
  child.stdout.setEncoding("utf8").on("data", (chunk) => {
    stdout += chunk;
  });
  const send = (message) => child.stdin.write(`${JSON.stringify(message)}\n`);
  send({
    jsonrpc: "2.0",
    id: 1,
    method: "initialize",
    params: { protocolVersion: "2024-11-05", capabilities: {} },
  });
  send({
    jsonrpc: "2.0",
    id: 2,
    method: "tools/call",
    params: { name: "spaces_list_content", arguments: { status: "review" } },
  });
  send({
    jsonrpc: "2.0",
    id: 3,
    method: "tools/call",
    params: { name: "spaces_get_content", arguments: { content: "content:card-1" } },
  });
  child.stdin.end();

  const exitCode = await new Promise((resolve, reject) => {
    child.once("error", reject);
    child.once("close", resolve);
  });
  assert.equal(exitCode, 0);
  const responses = stdout.trim().split("\n").map((line) => JSON.parse(line));
  assert.match(responses[1].result.content[0].text, /Launch post/);
  assert.match(responses[1].result.content[0].text, /Something is coming/);
  assert.match(responses[2].result.content[0].text, /content:card-1/);
  assert.match(responses[2].result.content[0].text, /Introduce the instrument/);
});

test("reads live messages, content, documents, private mail, and calendars from the paired desktop", async () => {
  const root = await mkdtemp(join(tmpdir(), "spaces-live-"));
  await mkdir(join(root, ".hq"));
  const dbPath = join(root, "spaces.db");
  const db = new DatabaseSync(dbPath);
  db.exec(`
    CREATE TABLE projects (id TEXT PRIMARY KEY, name TEXT);
    CREATE TABLE agents (id TEXT PRIMARY KEY, name TEXT);
    CREATE TABLE channels (id TEXT PRIMARY KEY, name TEXT);
    CREATE TABLE messages (
      id TEXT PRIMARY KEY, channel_id TEXT, author_type TEXT, author_name TEXT,
      content TEXT, status TEXT, parent_id TEXT, created_at INTEGER
    );
    CREATE TABLE content_items (
      id TEXT PRIMARY KEY, project_id TEXT, campaign TEXT, title TEXT, brief TEXT,
      copy TEXT, platform TEXT, connection_id TEXT, status TEXT, scheduled_at INTEGER,
      published_url TEXT, media_url TEXT, publish_error TEXT, updated_at INTEGER,
      created_at INTEGER, agent_id TEXT
    );
    CREATE TABLE documents (
      id TEXT PRIMARY KEY, project_id TEXT, title TEXT, path TEXT, tags TEXT,
      body TEXT, visibility TEXT, pinned INTEGER, updated_at INTEGER
    );
    CREATE TABLE mail_threads (
      id TEXT PRIMARY KEY, folder TEXT, subject TEXT, from_name TEXT,
      from_email TEXT, to_email TEXT, preview TEXT, body TEXT, unread INTEGER,
      received_at INTEGER, updated_at INTEGER
    );
    CREATE TABLE calendars (id TEXT PRIMARY KEY, name TEXT);
    CREATE TABLE events (
      id TEXT PRIMARY KEY, calendar_id TEXT, title TEXT, description TEXT,
      location TEXT, starts_at INTEGER, ends_at INTEGER, source TEXT, status TEXT
    );
    CREATE TABLE integration_accounts (
      id TEXT PRIMARY KEY, category TEXT, provider TEXT, label TEXT, handle TEXT,
      status TEXT, metadata TEXT
    );
  `);
  db.exec(`
    INSERT INTO projects VALUES ('project-1', 'archii');
    INSERT INTO agents VALUES ('agent-1', 'Codex');
    INSERT INTO channels VALUES ('channel-1', 'general');
    INSERT INTO messages VALUES (
      'message-1','channel-1','user','Lauren','Use the live board.','done','',80
    );
    INSERT INTO messages VALUES (
      'message-2','channel-1','agent','Codex','The board is current.','done','message-1',81
    );
    INSERT INTO content_items VALUES (
      'card-1','project-1','Reveal','Launch post','Introduce the instrument.',
      'Something is coming.','instagram','connection-1','review',0,'',
      'https://example.com/launch.png','',100,90,'agent-1'
    );
    INSERT INTO documents VALUES (
      'doc-1','project-1','Operating charter','Company/Operating charter.md',
      'company,runbook','Use the board.','workspace',1,100
    );
    INSERT INTO mail_threads VALUES (
      'mail-1','inbox','Launch approval','Lauren','lauren@example.com',
      'team@example.com','Please approve','Please approve the launch.',1,100,100
    );
    INSERT INTO calendars VALUES ('cal-1','Team');
    INSERT INTO events VALUES (
      'event-1','cal-1','Launch review','Review the post','Remote',
      2000000000000,2000003600000,'google','confirmed'
    );
    INSERT INTO integration_accounts VALUES (
      'portal-connection-1','social','meta','Instagram','archiiai','connected',
      '{"connectionId":"connection-1","projectLinks":[{"projectId":"project-1","isDefault":true}]}'
    );
  `);
  db.close();

  const toolNames = [
    "spaces_list_messages",
    "spaces_list_content",
    "spaces_get_content",
    "spaces_list_documents",
    "spaces_get_document",
    "spaces_list_mail",
    "spaces_get_mail",
    "spaces_list_calendar",
    "spaces_list_social_accounts",
  ];
  await writeFile(
    join(root, ".hq", "mcp-tools.json"),
    `${JSON.stringify({
      version: 1,
      tools: toolNames.map((name) => ({
        name,
        description: name,
        effect: "auto",
        readOnly: true,
        inputSchema: { type: "object", properties: {}, additionalProperties: true },
      })),
    })}\n`,
  );

  const child = spawn(process.execPath, [server.pathname, root], {
    cwd: root,
    env: {
      ...process.env,
      SPACES_PROJECT_ID: "project-1",
      SPACES_CHANNEL_ID: "channel-1",
      SPACES_DB_PATH: dbPath,
    },
    stdio: ["pipe", "pipe", "pipe"],
  });
  let stdout = "";
  child.stdout.setEncoding("utf8").on("data", (chunk) => {
    stdout += chunk;
  });
  const calls = [
    ["spaces_list_messages", {}],
    ["spaces_list_content", {}],
    ["spaces_get_content", { content: "content:card-1" }],
    ["spaces_list_documents", {}],
    ["spaces_get_document", { document: "document:doc-1" }],
    ["spaces_list_mail", { folder: "inbox" }],
    ["spaces_get_mail", { mail: "mail:mail-1" }],
    [
      "spaces_list_calendar",
      { from: "2033-05-17T00:00:00.000Z", to: "2033-05-19T00:00:00.000Z" },
    ],
    ["spaces_list_social_accounts", {}],
  ];
  calls.forEach(([name, args], index) => {
    child.stdin.write(
      `${JSON.stringify({
        jsonrpc: "2.0",
        id: index + 1,
        method: "tools/call",
        params: { name, arguments: args },
      })}\n`,
    );
  });
  child.stdin.end();
  const exitCode = await new Promise((resolve, reject) => {
    child.once("error", reject);
    child.once("close", resolve);
  });
  assert.equal(exitCode, 0);
  const responses = stdout.trim().split("\n").map((line) => JSON.parse(line));
  const bodies = responses.map((response) => response.result.content[0].text);
  assert.match(bodies[0], /Use the live board/);
  assert.match(bodies[0], /reply_to=message:message-1/);
  assert.match(bodies[1], /Launch post/);
  assert.match(bodies[2], /Something is coming/);
  assert.match(bodies[3], /Operating charter/);
  assert.match(bodies[4], /Use the board/);
  assert.match(bodies[5], /Launch approval/);
  assert.match(bodies[6], /Please approve the launch/);
  assert.match(bodies[7], /Launch review/);
  assert.match(bodies[8], /instagram:archiiai/);
  assert.match(bodies[8], /archii \(default\)/);

  const cli = spawn(
    process.execPath,
    [
      server.pathname,
      root,
      "--call",
      "spaces_list_messages",
      JSON.stringify({ limit: 1 }),
    ],
    {
      cwd: root,
      env: {
        ...process.env,
        SPACES_PROJECT_ID: "project-1",
        SPACES_CHANNEL_ID: "channel-1",
        SPACES_DB_PATH: dbPath,
      },
      stdio: ["ignore", "pipe", "pipe"],
    },
  );
  let cliStdout = "";
  let cliStderr = "";
  cli.stdout.setEncoding("utf8").on("data", (chunk) => {
    cliStdout += chunk;
  });
  cli.stderr.setEncoding("utf8").on("data", (chunk) => {
    cliStderr += chunk;
  });
  const cliExit = await new Promise((resolve, reject) => {
    cli.once("error", reject);
    cli.once("close", resolve);
  });
  assert.equal(cliExit, 0, cliStderr);
  const cliResult = JSON.parse(cliStdout);
  assert.equal(cliResult.ok, true);
  assert.equal(cliResult.tool, "spaces_list_messages");
  assert.match(cliResult.output, /The board is current/);
});
